# Generated by Django 5.2.13 on 2026-05-04 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeetCodeAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(help_text='LeetCode username (case-insensitive).', max_length=64, unique=True)),
                ('sync_status', models.CharField(choices=[('pending', 'Pending'), ('ok', 'OK'), ('failed', 'Failed'), ('unverified', 'Unverified')], default='unverified', max_length=16)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('last_sync_error', models.TextField(blank=True)),
                ('total_solved', models.PositiveIntegerField(default=0)),
                ('easy_solved', models.PositiveIntegerField(default=0)),
                ('medium_solved', models.PositiveIntegerField(default=0)),
                ('hard_solved', models.PositiveIntegerField(default=0)),
                ('ranking', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leetcode_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LeetCode account',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.CharField(max_length=256)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=8)),
                ('topic_tags', models.JSONField(blank=True, default=list)),
                ('is_premium', models.BooleanField(default=False)),
                ('leetcode_id', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title_slug',),
                'indexes': [models.Index(fields=['difficulty'], name='leetcode_pr_difficu_fcbf9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solved_at', models.DateTimeField()),
                ('source', models.CharField(choices=[('auto', 'Auto'), ('manual', 'Manual')], default='auto', max_length=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='leetcode.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-solved_at',),
                'indexes': [models.Index(fields=['user', '-solved_at'], name='submission_user_date_idx'), models.Index(fields=['solved_at'], name='leetcode_su_solved__ed257a_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'problem', 'solved_at'), name='unique_user_problem_solved_at')],
            },
        ),
    ]
