# Generated by Django 5.2.14 on 2026-07-04 06:00

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverificationtoken',
            name='attempts',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='emailverificationtoken',
            name='otp',
            field=models.CharField(default=apps.users.models.generate_otp, max_length=6),
        ),
    ]
